version: "3"
services:
  web:
    image: nginx:alpine
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      app_net:
          ipv4_address: 172.23.7.20

  php:
    build: docker/php
    volumes:
      - .:/app
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      app_net:
        ipv4_address: 172.23.7.21

  mysql:
    image: mysql:5
    command: mysqld --sql_mode=""
    volumes:
    - ./docker/mysql/captive-portal.sql:/docker-entrypoint-initdb.d/captive-portal.sql
    environment:
    - MYSQL_ROOT_PASSWORD=secret_pass
    - MYSQL_DATABASE=captive-portal
    networks:
      app_net:
          ipv4_address: 172.23.7.22

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.7.1/24
